# Circle CI configuration file
# https://circleci.com/docs/

version: 2.1

commands:
  restore-deps:
    steps:
    - restore_cache:
        keys:
          - deps-{{ checksum "package-lock.json" }}
          - deps-
  cache-deps:
    steps:
    - save_cache:
        key: deps-{{ checksum "package-lock.json" }}
        paths:
          - node_modules
  install-deps:
    steps:
      - run:
          name: "Install dependencies"
          command: npm install
  run-test:
    parameters:
      TEST_NAME:
        default: ""
        type: string
      TEST_SUITE:
        default: ""
        type: string
    steps:
      - run:
          name: "Run test"
          command: |
            while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
            npm run test -- "<<parameters.TEST_NAME>>" "<<parameters.TEST_SUITE>>";
            kill %1

jobs:
  test:
    parameters:
      TEST_NAME:
        default: ""
        type: string
      TEST_SUITE:
        default: ""
        type: string
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - restore-deps
      - install-deps
      - cache-deps
      - run-test:
          TEST_NAME: << parameters.TEST_NAME >>
          TEST_SUITE: << parameters.TEST_SUITE >>

workflows:
  base:
    jobs:
      - test:
          name: "base"
          TEST_NAME: "base"
  bigNumber:
    jobs:
      - test:
          name: "bigNumber"
          TEST_NAME: "bigNumber"
  negativeNumber:
    jobs:
      - test:
          name: "negativeNumber"
          TEST_NAME: "negativeNumber"
  bigNumber-negativeNumber:
    jobs:
      - test:
          name: "bigNumber-negativeNumber"
          TEST_NAME: "bigNumber-negativeNumber"
  restAPI:
    jobs:
      - test:
          name: "restAPI"
          TEST_NAME: "restAPI"
  jiff_websockets:
    jobs:
      - test:
          name: "jiff_websockets"
          TEST_NAME: "jiff_websockets"
  bits:
    jobs:
      - test:
          name: "bits"
          TEST_NAME: "bits"
  fixedpoint-share:
    jobs:
      - test:
          name: "fixedpoint-share"
          TEST_NAME: "fixedpoint"
          TEST_SUITE: "share"
  fixedpoint-arithmetic:
    jobs:
      - test:
          name: "fixedpoint-arithmetic"
          TEST_NAME: "fixedpoint"
          TEST_SUITE: "arithmetic"
  fixedpoint-constant-arithmetic:
    jobs:
      - test:
          name: "fixedpoint-constant-arithmetic"
          TEST_NAME: "fixedpoint"
          TEST_SUITE: "constant arithmetic"
  fixedpoint-constant-comparison:
    jobs:
      - test:
          name: "fixedpoint-constant-comparison"
          TEST_NAME: "fixedpoint"
          TEST_SUITE: "constant comparison"
  fixedpoint-comparison:
    jobs:
      - test:
          name: "fixedpoint-comparison"
          TEST_NAME: "fixedpoint"
          TEST_SUITE: "comparison"
  fixedpoint-ifelse:
    jobs:
      - test:
          name: "fixedpoint-ifelse"
          TEST_NAME: "fixedpoint"
          TEST_SUITE: "ifelse"
  fixedpoint-negativeNumber-share:
    jobs:
      - test:
          name: "fixedpoint-negativeNumber-share"
          TEST_NAME: "fixedpoint-negativeNumber"
          TEST_SUITE: "share"
  fixedpoint-negativeNumber-arithmetic:
    jobs:
      - test:
          name: "fixedpoint-negativeNumber-arithmetic"
          TEST_NAME: "fixedpoint-negativeNumber"
          TEST_SUITE: "arithmetic"
  fixedpoint-negativeNumber-constant-arithmetic:
    jobs:
      - test:
          name: "fixedpoint-negativeNumber-constant-arithmetic"
          TEST_NAME: "fixedpoint-negativeNumber"
          TEST_SUITE: "constant arithmetic"
  fixedpoint-negativeNumber-constant-comparison:
    jobs:
      - test:
          name: "fixedpoint-negativeNumber-constant-comparison"
          TEST_NAME: "fixedpoint-negativeNumber"
          TEST_SUITE: "constant comparison"
  fixedpoint-negativeNumber-comparison:
    jobs:
      - test:
          name: "fixedpoint-negativeNumber-comparison"
          TEST_NAME: "fixedpoint-negativeNumber"
          TEST_SUITE: "comparison"
  fixedpoint-negativeNumber-ifelse:
    jobs:
      - test:
          name: "fixedpoint-negativeNumber-ifelse"
          TEST_NAME: "fixedpoint-negativeNumber"
          TEST_SUITE: "ifelse"