# Circle CI configuration file
# https://circleci.com/docs/

version: 2.1

commands:
  checkout-code:
    steps:
    - run:
        name: Checkout code
        command: |
          mkdir ~/.ssh
          chmod 0700 ~/.ssh
          sudo printf "%s" "github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" >> ~/.ssh/known_hosts
          sudo chmod 0600 ~/.ssh/known_hosts
          cd /home/circleci
          rm -r -f project
          git clone $CIRCLE_REPOSITORY_URL -b ${CIRCLE_BRANCH} --single-branch --depth 1
          mv jiff/ project/
          cd project/
  restore-deps:
    steps:
      - restore_cache:
          keys:
            - deps-{{ checksum "package-lock.json" }}
            - deps-
  cache-deps:
    steps:
      - save_cache:
          key: deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  install-deps:
    steps:
      - run:
          name: "Install dependencies"
          command: npm install
  run-test:
    parameters:
      TEST_NAME:
        default: ""
        type: string
      TEST_SUITE:
        default: ""
        type: string
    steps:
      - run:
          name: "Run test"
          command: |
            while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
            npm run test -- "<<parameters.TEST_NAME>>" "<<parameters.TEST_SUITE>>";
            kill %1
  run-demo:
    parameters:
      DEMO_NAME:
        default: "*"
        type: string
    steps:
      - run:
          name: "Run demo"
          command: npm run-script test-demo -- \*

jobs:
  test:
    parameters:
      TEST_NAME:
        default: ""
        type: string
      TEST_SUITE:
        default: ""
        type: string
    docker:
      - image: cimg/node:current
    steps:
      - checkout-code
      - restore-deps
      - install-deps
      - cache-deps
      - run-test:
          TEST_NAME: << parameters.TEST_NAME >>
          TEST_SUITE: << parameters.TEST_SUITE >>
  run-demos:
    parameters:
      DEMO_NAME:
        default: "*"
        type: string
    docker:
      - image: cimg/node:current
    steps:
      - checkout-code
      - restore-deps
      - install-deps
      - cache-deps
      - run-demo:
          DEMO_NAME: << parameters.DEMO_NAME >>

workflows:
  base:
    jobs:
      - test:
          name: "base"
          TEST_NAME: "base"
  bigNumber:
    jobs:
      - test:
          name: "bigNumber"
          TEST_NAME: "bigNumber"
  negativeNumber:
    jobs:
      - test:
          name: "negativeNumber"
          TEST_NAME: "negativeNumber"
  bigNumber-negativeNumber:
    jobs:
      - test:
          name: "bigNumber-negativeNumber"
          TEST_NAME: "bigNumber-negativeNumber"
  restAPI:
    jobs:
      - test:
          name: "restAPI"
          TEST_NAME: "restAPI"
  jiff_websockets:
    jobs:
      - test:
          name: "jiff_websockets"
          TEST_NAME: "jiff_websockets"
  bits-arithmetic:
    jobs:
      - test:
          name: "bits-arithmetic"
          TEST_NAME: "bits"
          TEST_SUITE: "arithmetic"
  bits-constant-arithmetic:
    jobs:
      - test:
          name: "bits-constant-arithmetic"
          TEST_NAME: "bits"
          TEST_SUITE: "constant arithmetic"
  bits-arithmetic-lengths:
    jobs:
      - test:
          name: "bits-arithmetic-lengths"
          TEST_NAME: "bits"
          TEST_SUITE: "arithmetic lengths"
  bits-constant-comparison:
    jobs:
      - test:
          name: "bits-constant-comparison"
          TEST_NAME: "bits"
          TEST_SUITE: "constant comparison"
  bits-comparison:
    jobs:
      - test:
          name: "bits-comparison"
          TEST_NAME: "bits"
          TEST_SUITE: "comparison"
  bits-decomposition:
    jobs:
      - test:
          name: "bits-decomposition"
          TEST_NAME: "bits"
          TEST_SUITE: "decomposition"
  bits-comparison-lengths:
    jobs:
      - test:
          name: "bits-comparison-lengths"
          TEST_NAME: "bits"
          TEST_SUITE: "comparison lengths"
  bits-rejection-sampling:
    jobs:
      - test:
          name: "bits-rejection-sampling"
          TEST_NAME: "bits"
          TEST_SUITE: "rejection sampling"
  fixedpoint-share:
    jobs:
      - test:
          name: "fixedpoint-share"
          TEST_NAME: "fixedpoint"
          TEST_SUITE: "share"
  fixedpoint-arithmetic:
    jobs:
      - test:
          name: "fixedpoint-arithmetic"
          TEST_NAME: "fixedpoint"
          TEST_SUITE: "arithmetic"
  fixedpoint-constant-arithmetic:
    jobs:
      - test:
          name: "fixedpoint-constant-arithmetic"
          TEST_NAME: "fixedpoint"
          TEST_SUITE: "constant arithmetic"
  fixedpoint-constant-comparison:
    jobs:
      - test:
          name: "fixedpoint-constant-comparison"
          TEST_NAME: "fixedpoint"
          TEST_SUITE: "constant comparison"
  fixedpoint-comparison:
    jobs:
      - test:
          name: "fixedpoint-comparison"
          TEST_NAME: "fixedpoint"
          TEST_SUITE: "comparison"
  fixedpoint-ifelse:
    jobs:
      - test:
          name: "fixedpoint-ifelse"
          TEST_NAME: "fixedpoint"
          TEST_SUITE: "ifelse"
  fixedpoint-negativeNumber-share:
    jobs:
      - test:
          name: "fixedpoint-negativeNumber-share"
          TEST_NAME: "fixedpoint-negativeNumber"
          TEST_SUITE: "share"
  fixedpoint-negativeNumber-arithmetic:
    jobs:
      - test:
          name: "fixedpoint-negativeNumber-arithmetic"
          TEST_NAME: "fixedpoint-negativeNumber"
          TEST_SUITE: "arithmetic"
  fixedpoint-negativeNumber-constant-arithmetic:
    jobs:
      - test:
          name: "fixedpoint-negativeNumber-constant-arithmetic"
          TEST_NAME: "fixedpoint-negativeNumber"
          TEST_SUITE: "constant arithmetic"
  fixedpoint-negativeNumber-constant-comparison:
    jobs:
      - test:
          name: "fixedpoint-negativeNumber-constant-comparison"
          TEST_NAME: "fixedpoint-negativeNumber"
          TEST_SUITE: "constant comparison"
  fixedpoint-negativeNumber-comparison:
    jobs:
      - test:
          name: "fixedpoint-negativeNumber-comparison"
          TEST_NAME: "fixedpoint-negativeNumber"
          TEST_SUITE: "comparison"
  fixedpoint-negativeNumber-ifelse:
    jobs:
      - test:
          name: "fixedpoint-negativeNumber-ifelse"
          TEST_NAME: "fixedpoint-negativeNumber"
          TEST_SUITE: "ifelse"
  demos:
    jobs:
      - run-demos