name: Build & Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - master
  tags:
    - v*
    - v*.*
    - v*.*.*
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test